#!/usr/bin/env bash

DISTRIBUTION=`cat dist 2>/dev/null`

if [ -z "$DISTRIBUTION" ]; then
	echo "No distribution?"
	exit 1
fi

case "$DISTRIBUTION" in
	redhat|centos)
		if ! rpm -qa | grep '^cppunit-[0-9]'; then
			rm -f cppunit-1.12.0-4.el5.1.x86_64.rpm
			wget http://ftp.acc.umu.se/mirror/fedora/epel/5/x86_64/cppunit-1.12.0-4.el5.1.x86_64.rpm &&
			sudo -nA rpm -i cppunit-1.12.0-4.el5.1.x86_64.rpm ||
			exit 1
		fi
		if ! rpm -qa | grep '^cppunit-devel-[0-9]'; then
			rm -f cppunit-devel-1.12.0-4.el5.1.x86_64.rpm
			wget http://ftp.acc.umu.se/mirror/fedora/epel/5/x86_64/cppunit-devel-1.12.0-4.el5.1.x86_64.rpm &&
			sudo -nA rpm -i cppunit-devel-1.12.0-4.el5.1.x86_64.rpm ||
			exit 1
		fi
		;;

	sunos)
		;;
esac

echo "DONE"
exit 0
