#!/usr/bin/env bash

DISTRIBUTION=`cat dist 2>/dev/null`

if [ -z "$DISTRIBUTION" ]; then
	echo "No distribution?"
	exit 1
fi
			
case "$DISTRIBUTION" in
	ubuntu)
		export LC_ALL="en_US.UTF-8"
		export LANGUAGE="en_US.UTF-8"
		sudo -nA apt-get -y autoremove ||
		exit 1
		uname=`uname -r | sed 's%-\(server\|generic\)%%'`
		purge_rc=`dpkg -l | grep '^rc' | awk '{ print $2 }'`
		purge_kern=`dpkg -l | grep 'linux-\(headers\|image\)-[0-9]' | grep -v "$uname" | awk '{ print $2 }'`
		if [ -n "$purge_rc" -o -n "$purge_kern" ]; then
			sudo -nA apt-get -y purge $purge_rc $purge_kern ||
			exit 1
		fi
		sudo -nA apt-get clean ||
		exit 1
		;;

	redhat|centos)
		uname=`uname -r | sed 's%\.x86_64%%'`
		remove=`rpm -qa | grep '^kernel' | grep -v "$uname"`
		if [ -n "$remove" ]; then
			sudo -nA yum -y remove $remove ||
			exit 1
		fi
		sudo -nA yum -y clean packages &&
		sudo -nA yum -y clean expire-cache ||
		exit 1
		;;


	sunos)
		sudo -nA rm -rf ~root/.cpan/build ||
		exit 1
		;;

	suse)
		sudo -nA rm -rf ~root/.cpan/build &&
		sudo -nA zypper --non-interactive-include-reboot-patches -n clean ||
		exit 1
		;;
esac

echo "DONE"
exit 0
