#!/usr/bin/env bash

DISTRIBUTION=`cat dist 2>/dev/null`

if [ -z "$DISTRIBUTION" ]; then
	echo "No distribution?"
	exit 1
fi
			
case "$DISTRIBUTION" in
	ubuntu)
		export LC_ALL="en_US.UTF-8"
		export LANGUAGE="en_US.UTF-8"
		sudo apt-get -y autoremove ||
		exit 1
		uname=`uname -r | sed 's%-\(server\|generic\)%%'`
		purge_rc=`dpkg -l | grep '^rc' | awk '{ print $2 }'`
		purge_kern=`dpkg -l | grep 'linux-\(headers\|image\)-[0-9]' | grep -v "$uname" | awk '{ print $2 }'`
		if [ -n "$purge_rc" -o -n "$purge_kern" ]; then
			sudo apt-get -y purge $purge_rc $purge_kern ||
			exit 1
		fi
		sudo apt-get clean ||
		exit 1
		;;
esac

echo "DONE"
exit 0
